/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p.o.o.preliminardesign;

/**
 *
 * @author Vicente Hernandez
 */
public class Biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form Biblioteca
     */
    public Biblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBiblioteca = new javax.swing.JLabel();
        lblJuegosBiblioteca = new javax.swing.JLabel();
        CBXFiltrado = new javax.swing.JComboBox<>();
        lblFiltrar = new javax.swing.JLabel();
        pnPrincipal = new javax.swing.JPanel();
        pnUpDuty = new javax.swing.JPanel();
        lblUpDuty = new javax.swing.JLabel();
        pnCoco = new javax.swing.JPanel();
        lblCoco = new javax.swing.JLabel();
        pnWhoG = new javax.swing.JPanel();
        lblWhoG = new javax.swing.JLabel();
        lblFallG = new javax.swing.JLabel();
        pnFallG = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        lblBiblioteca.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblBiblioteca.setText("Biblioteca");

        lblJuegosBiblioteca.setFont(new java.awt.Font("Trebuchet MS", 2, 16)); // NOI18N
        lblJuegosBiblioteca.setText("Juegos en tu biblioteca");

        CBXFiltrado.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CBXFiltrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genero", "Año de lanzamiento", "Horas jugadas", "Favoritos" }));
        CBXFiltrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXFiltradoActionPerformed(evt);
            }
        });

        lblFiltrar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblFiltrar.setText("Filtrar por");

        pnUpDuty.setBackground(new java.awt.Color(51, 51, 255));
        pnUpDuty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 52, 255), 5, true));
        pnUpDuty.setToolTipText("");

        javax.swing.GroupLayout pnUpDutyLayout = new javax.swing.GroupLayout(pnUpDuty);
        pnUpDuty.setLayout(pnUpDutyLayout);
        pnUpDutyLayout.setHorizontalGroup(
            pnUpDutyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        pnUpDutyLayout.setVerticalGroup(
            pnUpDutyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        lblUpDuty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUpDuty.setText("Upsin´s Duty");

        pnCoco.setBackground(new java.awt.Color(51, 51, 255));
        pnCoco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 55, 255), 5, true));
        pnCoco.setToolTipText("");

        javax.swing.GroupLayout pnCocoLayout = new javax.swing.GroupLayout(pnCoco);
        pnCoco.setLayout(pnCocoLayout);
        pnCocoLayout.setHorizontalGroup(
            pnCocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        pnCocoLayout.setVerticalGroup(
            pnCocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblCoco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCoco.setText("Cocotiza");

        pnWhoG.setBackground(new java.awt.Color(51, 51, 255));
        pnWhoG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 55, 255), 5, true));
        pnWhoG.setToolTipText("");

        javax.swing.GroupLayout pnWhoGLayout = new javax.swing.GroupLayout(pnWhoG);
        pnWhoG.setLayout(pnWhoGLayout);
        pnWhoGLayout.setHorizontalGroup(
            pnWhoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        pnWhoGLayout.setVerticalGroup(
            pnWhoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblWhoG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWhoG.setText("Who´s Gamboa?");

        lblFallG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFallG.setText("Falling Grandmas");

        pnFallG.setBackground(new java.awt.Color(51, 51, 255));
        pnFallG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 55, 255), 5, true));
        pnFallG.setToolTipText("");

        javax.swing.GroupLayout pnFallGLayout = new javax.swing.GroupLayout(pnFallG);
        pnFallG.setLayout(pnFallGLayout);
        pnFallGLayout.setHorizontalGroup(
            pnFallGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        pnFallGLayout.setVerticalGroup(
            pnFallGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addComponent(pnUpDuty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(pnCoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(pnWhoG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addComponent(lblUpDuty)
                        .addGap(51, 51, 51)
                        .addComponent(lblCoco)
                        .addGap(39, 39, 39)
                        .addComponent(lblWhoG)))
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnFallG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFallG))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(pnFallG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUpDuty)
                            .addComponent(lblCoco)
                            .addComponent(lblWhoG)
                            .addComponent(lblFallG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnUpDuty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnCoco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnWhoG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBiblioteca)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblJuegosBiblioteca)
                        .addGap(73, 73, 73)
                        .addComponent(lblFiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBXFiltrado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblBiblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJuegosBiblioteca)
                    .addComponent(lblFiltrar)
                    .addComponent(CBXFiltrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBXFiltradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXFiltradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBXFiltradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBXFiltrado;
    private javax.swing.JLabel lblBiblioteca;
    private javax.swing.JLabel lblCoco;
    private javax.swing.JLabel lblFallG;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JLabel lblJuegosBiblioteca;
    private javax.swing.JLabel lblUpDuty;
    private javax.swing.JLabel lblWhoG;
    private javax.swing.JPanel pnCoco;
    private javax.swing.JPanel pnFallG;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JPanel pnUpDuty;
    private javax.swing.JPanel pnWhoG;
    // End of variables declaration//GEN-END:variables
}
