/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package p.o.o.preliminardesign;

/**
 *
 * @author irvin
 */
public class DevFormat extends javax.swing.JPanel {

    /**
     * Creates new form DevFormat
     */
    public DevFormat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitle = new javax.swing.JLabel();
        LblIcon = new javax.swing.JLabel();
        LblUser = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        LblPassword = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        LblCPassword = new javax.swing.JLabel();
        CPassword = new javax.swing.JPasswordField();
        LblHName = new javax.swing.JLabel();
        TxtHName = new javax.swing.JTextField();
        LblHIcon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(1, 44, 98));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblTitle.setBackground(new java.awt.Color(0, 0, 153));
        LblTitle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LblTitle.setForeground(new java.awt.Color(255, 255, 255));
        LblTitle.setText("STAAM");
        add(LblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 36, -1, -1));

        LblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\irvin\\Downloads\\UPSIN Reception\\6th. Scene\\P.O.O\\STAAM.png")); // NOI18N
        LblIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblIcon.setPreferredSize(new java.awt.Dimension(512, 512));
        add(LblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 21, 65, 60));

        LblUser.setForeground(new java.awt.Color(255, 255, 255));
        LblUser.setText("Publishing House Name");
        add(LblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 116, -1, -1));

        TxtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });
        add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 144, 200, -1));

        LblPassword.setForeground(new java.awt.Color(255, 255, 255));
        LblPassword.setText("Email");
        add(LblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 174, -1, -1));

        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 202, 200, -1));

        LblCPassword.setForeground(new java.awt.Color(255, 255, 255));
        LblCPassword.setText("Password");
        add(LblCPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 232, -1, -1));

        CPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(CPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 260, 200, -1));

        LblHName.setForeground(new java.awt.Color(255, 255, 255));
        LblHName.setText("Confirm Password");
        add(LblHName, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 290, -1, -1));

        TxtHName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtHName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHNameActionPerformed(evt);
            }
        });
        add(TxtHName, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 320, 200, -1));

        LblHIcon.setForeground(new java.awt.Color(255, 255, 255));
        LblHIcon.setText("Publishing House logo");
        add(LblHIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 116, -1, -1));

        jButton1.setText("CreateAccount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 356, -1, -1));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Insert here your logo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 144, -1, 235));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUserActionPerformed

    private void TxtHNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CPassword;
    private javax.swing.JLabel LblCPassword;
    private javax.swing.JLabel LblHIcon;
    private javax.swing.JLabel LblHName;
    private javax.swing.JLabel LblIcon;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JLabel LblUser;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField TxtHName;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
