/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import p.o.o.preliminardesign.CarritoClase;
import p.o.o.preliminardesign.Database;
import p.o.o.preliminardesign.SessionManager;
import p.o.o.preliminardesign.User;
import p.o.o.preliminardesign.windowCreator;

/**
 *
 * @author chuyi
 */
public class Carrito extends javax.swing.JFrame { 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Carrito.class.getName());
     double subTotalSum;
     User currUser;
    public Carrito() {
        initComponents();
        JPanel gamesContainer = new JPanel();
        gamesContainer.setLayout(new BoxLayout(gamesContainer, BoxLayout.Y_AXIS));
        this.subTotalSum = CarritoClase.showALlCartGames(this,gamesContainer, paymentContainer, sizeCartLabel, subTotal);
        JScrollPane scrollPane = new JScrollPane(gamesContainer);
            scrollPane.setPreferredSize(new Dimension(500, 200));
             scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
             scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
             scrollPane.getVerticalScrollBar().setUnitIncrement(16);
             placeHolderCart.setLayout(new GridLayout());
            placeHolderCart.add(scrollPane);
            String query = "SELECT * FROM Usuarios WHERE ID = ?";
            currUser = (User) SessionManager.getCurrentUser();
            try{
                Connection conn = Database.getConnection();
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setInt(1, currUser.getID());
                ResultSet rs = stmt.executeQuery();
                rs.next();
                currUser.setBalance(rs.getDouble("Balance"));
            }
             catch (SQLException e) {
                    e.printStackTrace();
                }
    }
    
    public void setSubTotal(double subTotalSum){
        this.subTotalSum = subTotalSum;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        placeHolderCart = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sizeCartLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        paymentContainer = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        subTotal = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(1, 44, 98));

        jPanel1.setBackground(new java.awt.Color(1, 44, 98));

        placeHolderCart.setBackground(new java.awt.Color(1, 44, 98));

        javax.swing.GroupLayout placeHolderCartLayout = new javax.swing.GroupLayout(placeHolderCart);
        placeHolderCart.setLayout(placeHolderCartLayout);
        placeHolderCartLayout.setHorizontalGroup(
            placeHolderCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        placeHolderCartLayout.setVerticalGroup(
            placeHolderCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Your Cart");

        sizeCartLabel.setFont(new java.awt.Font("Adwaita Sans", 1, 18)); // NOI18N
        sizeCartLabel.setForeground(new java.awt.Color(255, 255, 255));
        sizeCartLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sizeCartLabel.setText("Size");

        jButton2.setBackground(new java.awt.Color(1, 44, 98));
        jButton2.setFont(new java.awt.Font("Adwaita Sans", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("getBack");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        paymentContainer.setBackground(new java.awt.Color(1, 44, 98));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Subtotal");

        subTotal.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        subTotal.setForeground(new java.awt.Color(255, 255, 255));
        subTotal.setText("$24.99");

        payButton.setBackground(new java.awt.Color(51, 255, 0));
        payButton.setForeground(new java.awt.Color(51, 51, 51));
        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentContainerLayout = new javax.swing.GroupLayout(paymentContainer);
        paymentContainer.setLayout(paymentContainerLayout);
        paymentContainerLayout.setHorizontalGroup(
            paymentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(subTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payButton))
        );
        paymentContainerLayout.setVerticalGroup(
            paymentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(subTotal)
                    .addComponent(payButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paymentContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placeHolderCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sizeCartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addGap(110, 110, 110)
                                    .addComponent(jLabel3))))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sizeCartLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(placeHolderCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paymentContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        windowCreator.openJframeWindow(new Tienda() , "Store");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
       if(this.subTotalSum > currUser.getBalance()){
            JOptionPane.showMessageDialog(null , "Not enough Balance" );
            return;
       }
       String query = "UPDATE Usuarios SET Balance = Balance - ? WHERE ID = ? ";
       try{
                Connection conn = Database.getConnection();
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setDouble(1, this.subTotalSum);
                 stmt.setDouble(2,this.currUser.getID());
                stmt.executeUpdate();
                
                stmt = conn.prepareStatement("SELECT Balance FROM Usuarios where ID = ?");
                stmt.setInt(1, currUser.getID());
                ResultSet rs = stmt.executeQuery();
                rs.next();
                currUser.setBalance(rs.getDouble("Balance"));
                
                //Agregar juegos del carrtio a biblioteca
                 stmt = conn.prepareStatement("SELECT * FROM Carrito AS C INNER JOIN Juegos AS J ON C.ID_Juego = J.ID_Juegos where ID_Usuario = ?");
                 stmt.setInt(1,currUser.getID());
                 rs = stmt.executeQuery();
                 
                 while(rs.next()){
                        PreparedStatement stmt2 = conn.prepareCall("{CALL fromCartToLibrary(?,?)}");
                        stmt2.setInt(1, currUser.getID());
                        stmt2.setInt(2, rs.getInt("C.ID_Juego"));
                        stmt2.executeUpdate();
                         JOptionPane.showMessageDialog(null , rs.getString("J.Nombre") + " was added succesfully to your library." );
                 }
                 
            }
             catch (SQLException e) {
                     JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
                }
       
             this.dispose();
             windowCreator.openJframeWindow(new Tienda(), "Shop");
       
    }//GEN-LAST:event_payButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Carrito().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton payButton;
    private javax.swing.JPanel paymentContainer;
    private javax.swing.JPanel placeHolderCart;
    private javax.swing.JLabel sizeCartLabel;
    private javax.swing.JLabel subTotal;
    // End of variables declaration//GEN-END:variables
}
