/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import p.o.o.preliminardesign.Database;
import p.o.o.preliminardesign.timerThread;
import p.o.o.preliminardesign.windowCreator;

/**
 *
 * @author Vicente Hernandez
 */
public class gamePlay extends javax.swing.JFrame {
    String gameName;
    int idGame;
    int idSession;
    timerThread thread;
    /**
     * @param idGame
     * @param idSession
     */
    public gamePlay(int idGame , int idSession) {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                closeGameplay();
                dispose();
            }

            @Override
            public void windowClosed(WindowEvent e) {
                closeGameplay();
                windowCreator.openJframeWindow(new GameBInfo(idGame), gameName);
            }
        });
        this.idGame = idGame;
        this.idSession = idSession;
        String query = "SELECT * FROM Juegos WHERE ID_Juegos = ?";
        Color[] colors = {
            Color.RED,
            Color.BLUE,
            Color.GREEN,
            Color.YELLOW,
            Color.ORANGE,
            Color.PINK,
            Color.CYAN,
            Color.MAGENTA,
            Color.LIGHT_GRAY,
            Color.DARK_GRAY
        };

        // Create a Random object
        Random rand = new Random();

        // Pick a random color from the array
        Color randomColor = colors[rand.nextInt(colors.length)];
        
        for (Component comp : textPanel.getComponents()) {
            if (comp instanceof JLabel jLabel) {
                jLabel.setForeground(randomColor);
            }
            else if((comp instanceof JButton jButton)){
                jButton.setForeground(randomColor);
            }
        }
        
        try{
            Connection conn = Database.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query);
             stmt.setInt(1,idGame);
             ResultSet rs = stmt.executeQuery();
             rs.next();
             this.gameName = rs.getString("Nombre");
             GameName.setText(this.gameName );
        }
         catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
         }
        
        timerThread timer = new timerThread(timerPanel);
        this.thread = timer;
        timer.start();
    }
    
    public gamePlay() {
        initComponents();
    }
    
    private void closeGameplay(){
        int minutes = this.thread.getSeconds() / 60;
        this.thread.stopThread();  // signal thread to stop
        
        
        try{
            Connection conn = Database.getConnection();
            PreparedStatement stmt;
            if(minutes > 0){
                stmt = conn.prepareStatement("UPDATE SesionJuego SET DuracionSesion = ? WHERE ID_Sesion = ?");
                stmt.setInt(1, minutes);
                stmt.setInt(2, this.idSession);
                
            }
            else{
                stmt = conn.prepareStatement("DELETE FROM SesionJuego WHERE ID_Sesion = ?");
                stmt.setInt(1, this.idSession);
            }
            stmt.executeUpdate();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
         }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timerPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        btnJugar5 = new javax.swing.JButton();
        btnJugar2 = new javax.swing.JButton();
        GameName = new javax.swing.JLabel();
        ExitLabel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(1, 44, 98));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        timerPanel.setFont(new java.awt.Font("Adwaita Sans", 1, 18)); // NOI18N
        timerPanel.setForeground(new java.awt.Color(0, 0, 0));
        timerPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerPanel.setText("00:00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timerPanel)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        textPanel.setBackground(new java.awt.Color(102, 102, 102));

        btnJugar.setBackground(new java.awt.Color(102, 102, 102));
        btnJugar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 102, 0));
        btnJugar.setText("Campaign");
        btnJugar.setBorder(null);

        btnJugar5.setBackground(new java.awt.Color(102, 102, 102));
        btnJugar5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnJugar5.setForeground(new java.awt.Color(255, 102, 0));
        btnJugar5.setText("MultiPlayer");
        btnJugar5.setBorder(null);

        btnJugar2.setBackground(new java.awt.Color(102, 102, 102));
        btnJugar2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnJugar2.setForeground(new java.awt.Color(255, 102, 0));
        btnJugar2.setText("Settings");
        btnJugar2.setBorder(null);
        btnJugar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugar2ActionPerformed(evt);
            }
        });

        GameName.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        GameName.setForeground(new java.awt.Color(255, 102, 0));
        GameName.setText("Cocotiza");

        ExitLabel.setBackground(new java.awt.Color(102, 102, 102));
        ExitLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ExitLabel.setForeground(new java.awt.Color(255, 102, 0));
        ExitLabel.setText("Exit");
        ExitLabel.setBorder(null);
        ExitLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJugar5)
                    .addComponent(btnJugar2)
                    .addComponent(btnJugar)
                    .addComponent(GameName)
                    .addComponent(ExitLabel))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GameName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnJugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnJugar5)
                .addGap(18, 18, 18)
                .addComponent(btnJugar2)
                .addGap(18, 18, 18)
                .addComponent(ExitLabel)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJugar2ActionPerformed

    private void ExitLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitLabelActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gamePlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitLabel;
    private javax.swing.JLabel GameName;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnJugar2;
    private javax.swing.JButton btnJugar5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel textPanel;
    private javax.swing.JLabel timerPanel;
    // End of variables declaration//GEN-END:variables
}
