/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import java.awt.Window;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import p.o.o.preliminardesign.Database;
import p.o.o.preliminardesign.windowCreator;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import p.o.o.preliminardesign.SessionManager;
import p.o.o.preliminardesign.*;

/**
 *
 * @author irvin
 */
public class Login extends javax.swing.JPanel {
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblUser = new javax.swing.JLabel();
        usernameEntry = new javax.swing.JTextField();
        LblPassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        BtnLogin = new javax.swing.JButton();
        createAccount = new javax.swing.JButton();
        createPublisherAccount = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LblTitle = new javax.swing.JLabel();
        LblIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(1, 44, 98));

        LblUser.setFont(new java.awt.Font("Adwaita Sans", 0, 13)); // NOI18N
        LblUser.setForeground(new java.awt.Color(255, 255, 255));
        LblUser.setText("Sign in with account name or email");

        usernameEntry.setFont(new java.awt.Font("Adwaita Sans", 1, 14)); // NOI18N
        usernameEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usernameEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameEntryActionPerformed(evt);
            }
        });

        LblPassword.setFont(new java.awt.Font("Adwaita Sans", 0, 13)); // NOI18N
        LblPassword.setForeground(new java.awt.Color(255, 255, 255));
        LblPassword.setText("Password");

        password.setFont(new java.awt.Font("Adwaita Sans", 1, 14)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BtnLogin.setText("Sign In");
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLoginMouseClicked(evt);
            }
        });
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        createAccount.setBackground(new java.awt.Color(1, 44, 98));
        createAccount.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        createAccount.setForeground(new java.awt.Color(255, 255, 255));
        createAccount.setText("Dont have an Account?");
        createAccount.setBorder(null);
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });

        createPublisherAccount.setBackground(new java.awt.Color(1, 44, 98));
        createPublisherAccount.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        createPublisherAccount.setForeground(new java.awt.Color(255, 255, 255));
        createPublisherAccount.setText("I'm  a Developer...");
        createPublisherAccount.setBorder(null);
        createPublisherAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPublisherAccountActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(1, 44, 98));

        LblTitle.setBackground(new java.awt.Color(0, 0, 153));
        LblTitle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LblTitle.setForeground(new java.awt.Color(255, 255, 255));
        LblTitle.setText("STAAM");

        LblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblIcon.setPreferredSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(LblTitle)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LblTitle)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createAccount)
                                    .addComponent(createPublisherAccount))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnLogin))
                            .addComponent(LblPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameEntry, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblUser, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BtnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createPublisherAccount)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernameEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameEntryActionPerformed

    private void BtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLoginMouseClicked

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        String UsernameEmail , Password;
        UsernameEmail = usernameEntry.getText();
        Password = password.getText();
        boolean isEmail = false;
        if(Database.checkEmail(UsernameEmail )){
            isEmail= true;
        }
        else{
            if(!Database.checkValidUsername(UsernameEmail)){
                JOptionPane.showMessageDialog(null , "Username " + UsernameEmail + " Is Invalid" );
                return;
            }
          
         }
         String query = ( isEmail ) ? "SELECT * FROM Usuarios WHERE Email = ?": "SELECT * FROM Usuarios WHERE Username = ?";
         try {
                  Connection conn = Database.getConnection();
                  PreparedStatement stmt = conn.prepareStatement(query);
                  stmt.setString(1, UsernameEmail);
                   ResultSet rs = stmt.executeQuery();

                   if (!rs.next()) {
                        if (isEmail) {
                            JOptionPane.showMessageDialog(null , "A user with the email " + UsernameEmail +" doesn't exist");
                        } else {
                            JOptionPane.showMessageDialog(null , "A user with the username " + UsernameEmail +" doesn't exist");
                        }
                        return;
                    }

                    if (!Database.checkPassword(Password, rs.getString("password_hash"))) {
                        JOptionPane.showMessageDialog(null , "Incorrect password");
                        return;
                    }
                    byte[] imageBytes = rs.getBytes("fotoPerfil");
                    
                    ImageIcon profilePictureIcon =  (imageBytes != null && imageBytes.length > 0) ? new ImageIcon(imageBytes) : null;
                    GlobalUser currUser = new User(
                        rs.getInt("ID"),
                        rs.getString("Email"),
                        rs.getString("Username"),
                        rs.getDouble("Balance"),
                        rs.getDate("FechaCreacion").toString(),
                        rs.getString("Ubicacion"),
                        rs.getString("Telefono"),
                        profilePictureIcon 
                    );

                    SessionManager.login(currUser);

                    Window window = SwingUtilities.getWindowAncestor(this);
                    window.dispose();
                    windowCreator.openJframeWindow(new Tienda() , "Store");
                }
                catch (SQLException e) {
                    e.printStackTrace();
                }

    }//GEN-LAST:event_BtnLoginActionPerformed

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        windowCreator.openWindow("Create Account", 470, 600, new UserFormat());
        Window window = SwingUtilities.getWindowAncestor(this);
        window.dispose();
    }//GEN-LAST:event_createAccountActionPerformed

    private void createPublisherAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPublisherAccountActionPerformed
        windowCreator.openWindow("Create Publisher Account", 416, 350, new DevLogin());
        Window window = SwingUtilities.getWindowAncestor(this);
        window.dispose();
    }//GEN-LAST:event_createPublisherAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel LblIcon;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JLabel LblUser;
    private javax.swing.JButton createAccount;
    private javax.swing.JButton createPublisherAccount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField usernameEntry;
    // End of variables declaration//GEN-END:variables
}
