
package Views;

import java.awt.Image;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import p.o.o.preliminardesign.Database;
import p.o.o.preliminardesign.Game;
import p.o.o.preliminardesign.Publisher;
import p.o.o.preliminardesign.SessionManager;
import p.o.o.preliminardesign.windowCreator;

public class mainViewPublisher extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainViewPublisher.class.getName());
    String currGameName;
    int currIdGame;
    /**
     * Creates new form mainViewPublisher
     */
    public mainViewPublisher() {
        initComponents();
        publisherName.setText(SessionManager.getCurrentUser().getName());
        insidePanel.setVisible(false);
        
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem seeMore = new JMenuItem("Submit Update");
        popupMenu.add(seeMore);
        
        insidePanel.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            if (e.isPopupTrigger()) {
                popupMenu.show(e.getComponent(), e.getX(), e.getY());
            }
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            System.out.println("Released at: " + e.getPoint());
            if (e.isPopupTrigger()) {
                System.out.println("PopupTrigger on release");
                popupMenu.show(e.getComponent(), e.getX(), e.getY());
            }
        }
    });
        
        String query = "SELECT * FROM Publisher WHERE ID = ?";
        try{
            Connection conn = Database.getConnection();
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, String.valueOf(SessionManager.getCurrentUser().getID()));
            ResultSet rs = stmt.executeQuery();
            if(!rs.next()){
                return;
            }
            windowCreator.setIconLabel(logoPublisher, rs.getBytes("imagen"));
            try{
                    Publisher publisher = (Publisher) SessionManager.getCurrentUser();
                    ArrayList<Game> gamesArray = publisher.getAllGames();
                    for(Game game :  gamesArray ){
                        myGames.addItem(game.toString());
                    }
            }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null , "Error : " + e );
                        this.dispose();
              }
        }
        catch (SQLException e) {
             e.printStackTrace();
         }
        seeMore.addActionListener(e -> {
            this.dispose();
            windowCreator.openJframeWindow(new createUpdate(this.currIdGame), this.currGameName);
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        publisherName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoPublisher = new javax.swing.JLabel();
        submitGame = new javax.swing.JButton();
        myGames = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        mainPanelDashboard = new javax.swing.JPanel();
        insidePanel = new javax.swing.JPanel();
        gamePrice = new javax.swing.JLabel();
        gameSize = new javax.swing.JLabel();
        gameName = new javax.swing.JLabel();
        gameCover = new javax.swing.JLabel();
        launchDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GamesSold = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Earnings = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lastPlayers = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        jPanel1.setBackground(new java.awt.Color(1, 44, 98));
        jPanel1.setForeground(new java.awt.Color(1, 44, 98));

        publisherName.setFont(new java.awt.Font("Adwaita Sans", 1, 36)); // NOI18N
        publisherName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");

        submitGame.setBackground(new java.awt.Color(1, 44, 98));
        submitGame.setFont(new java.awt.Font("Adwaita Sans", 1, 18)); // NOI18N
        submitGame.setForeground(new java.awt.Color(255, 255, 255));
        submitGame.setText("Submit a Game");
        submitGame.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        submitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitGameActionPerformed(evt);
            }
        });

        myGames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Game" }));
        myGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGamesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Games");

        mainPanelDashboard.setBackground(new java.awt.Color(12, 83, 173));

        insidePanel.setBackground(new java.awt.Color(12, 83, 173));

        gamePrice.setFont(new java.awt.Font("Adwaita Sans", 0, 15)); // NOI18N
        gamePrice.setForeground(new java.awt.Color(255, 255, 255));
        gamePrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        gameSize.setFont(new java.awt.Font("Adwaita Sans", 0, 15)); // NOI18N
        gameSize.setForeground(new java.awt.Color(255, 255, 255));
        gameSize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        gameName.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        gameName.setForeground(new java.awt.Color(255, 255, 255));
        gameName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        launchDate.setFont(new java.awt.Font("Adwaita Sans", 0, 15)); // NOI18N
        launchDate.setForeground(new java.awt.Color(255, 255, 255));
        launchDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price");

        jLabel4.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Game Size");

        jLabel5.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Launch Date");

        jLabel6.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Games sold");

        GamesSold.setFont(new java.awt.Font("Adwaita Sans", 0, 15)); // NOI18N
        GamesSold.setForeground(new java.awt.Color(255, 255, 255));
        GamesSold.setText("0");
        GamesSold.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel7.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Earnings");

        Earnings.setFont(new java.awt.Font("Adwaita Sans", 0, 15)); // NOI18N
        Earnings.setForeground(new java.awt.Color(255, 255, 255));
        Earnings.setText("$0");
        Earnings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel8.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Players last 7 days");

        lastPlayers.setFont(new java.awt.Font("Adwaita Sans", 0, 15)); // NOI18N
        lastPlayers.setForeground(new java.awt.Color(255, 255, 255));
        lastPlayers.setText("0");
        lastPlayers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout insidePanelLayout = new javax.swing.GroupLayout(insidePanel);
        insidePanel.setLayout(insidePanelLayout);
        insidePanelLayout.setHorizontalGroup(
            insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insidePanelLayout.createSequentialGroup()
                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gameCover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insidePanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3)))
                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insidePanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(insidePanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53))))
            .addGroup(insidePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gamePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insidePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insidePanelLayout.createSequentialGroup()
                                .addComponent(GamesSold, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(Earnings, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(insidePanelLayout.createSequentialGroup()
                                .addComponent(gameSize, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(launchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(insidePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel7)
                        .addGap(65, 65, 65))))
        );
        insidePanelLayout.setVerticalGroup(
            insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameCover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gamePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameSize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(launchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GamesSold, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Earnings, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelDashboardLayout = new javax.swing.GroupLayout(mainPanelDashboard);
        mainPanelDashboard.setLayout(mainPanelDashboardLayout);
        mainPanelDashboardLayout.setHorizontalGroup(
            mainPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelDashboardLayout.setVerticalGroup(
            mainPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        logOut.setBackground(new java.awt.Color(255, 0, 0));
        logOut.setFont(new java.awt.Font("Adwaita Sans", 1, 14)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(myGames, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOut)
                        .addGap(47, 47, 47)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(publisherName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(submitGame))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addComponent(mainPanelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(logoPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(myGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logOut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publisherName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(submitGame)))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(mainPanelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitGameActionPerformed
        this.dispose();
        windowCreator.openJframeWindow(new submitGame() , "Submit a Game");
    }//GEN-LAST:event_submitGameActionPerformed

    private void myGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGamesActionPerformed
        String Selected =(String)  myGames.getSelectedItem();
            if(Selected.equals("Select a Game")){
             insidePanel.setVisible(false);
            }
        else{
            insidePanel.setVisible(true);
            insidePanel.revalidate();
            insidePanel.repaint();
            int idGame = Integer.parseInt(Selected.split("-")[0]);
            this.currIdGame = idGame;
            String query = "SELECT  * FROM Juegos WHERE ID_JUEGOS = ?";
            try{
                Connection conn = Database.getConnection();
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setInt(1, idGame);
                ResultSet rs = stmt.executeQuery();
                if(!rs.next()){
                         JOptionPane.showMessageDialog(null , "The game " +Selected +  "doesnt exist in the database" );
                         this.dispose();
                         return;
                }
                double Price = rs.getDouble("Precio");
                this.currGameName = rs.getString("Nombre");
                gameName.setText(this.currGameName);
                gamePrice.setText(String.valueOf(Price));
                gameSize.setText(Database.convertMBtoGB(rs.getInt("pesoJuego")));
                launchDate.setText(rs.getDate("FLanzamiento").toString());
                 byte[] imageBytes = rs.getBytes("fotoPortada");
                 if (imageBytes != null && imageBytes.length > 0) {
                    ImageIcon icon = new ImageIcon(imageBytes);
                    Image image = icon.getImage().getScaledInstance(gameCover.getWidth(),gameCover.getHeight(), Image.SCALE_SMOOTH);
                    gameCover.setIcon(new ImageIcon(image));
                }
                else{
                    JOptionPane.showMessageDialog(null , "Error loading the logo of the Publisher" );
                 this.dispose();
            }
                 stmt = conn.prepareStatement("SELECT copiasVendidas(?) as copiasVendidas;");
                 stmt.setInt(1,idGame);
                 rs = stmt.executeQuery();
                 rs.next();
                 int gameSold = rs.getInt("copiasVendidas");
                 GamesSold.setText(gameSold+"");
                 Earnings.setText("$"+(gameSold*Price));
                 
                 stmt = conn.prepareStatement("SELECT jugadoresUltimos7DIas(?) as Jugadores;");
                 stmt.setInt(1,idGame);
                 rs = stmt.executeQuery();
                 rs.next();
                 lastPlayers.setText(rs.getInt("Jugadores")+"");
                 
                
            }
             catch (SQLException e) {
             JOptionPane.showMessageDialog(null , "Error with SQL: " + e );
            }
        }
    }//GEN-LAST:event_myGamesActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        this.dispose();
        SessionManager.logout();
        windowCreator.openWindow("Login", 400, 350, new Login());
    }//GEN-LAST:event_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainViewPublisher().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Earnings;
    private javax.swing.JLabel GamesSold;
    private javax.swing.JLabel gameCover;
    private javax.swing.JLabel gameName;
    private javax.swing.JLabel gamePrice;
    private javax.swing.JLabel gameSize;
    private javax.swing.JPanel insidePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastPlayers;
    private javax.swing.JLabel launchDate;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel logoPublisher;
    private javax.swing.JPanel mainPanelDashboard;
    private javax.swing.JComboBox<String> myGames;
    private javax.swing.JLabel publisherName;
    private javax.swing.JButton submitGame;
    // End of variables declaration//GEN-END:variables
}
