/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import p.o.o.preliminardesign.Database;
import p.o.o.preliminardesign.GlobalUser;
import p.o.o.preliminardesign.SessionManager;
import p.o.o.preliminardesign.User;
import p.o.o.preliminardesign.windowCreator;

/**
 *
 * @author irvin
 */
public class UserFormat extends javax.swing.JPanel {

    /**
     * Creates new form DevFormat
     */
    public UserFormat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LblUser = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();
        createAccount = new javax.swing.JButton();
        LblUser1 = new javax.swing.JLabel();
        backToLogin = new javax.swing.JButton();
        emailEntry = new javax.swing.JTextField();
        usernameEntry = new javax.swing.JTextField();
        LblCPassword = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        LblIcon = new javax.swing.JLabel();
        LblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(1, 44, 98));

        jPanel2.setBackground(new java.awt.Color(1, 44, 98));

        LblUser.setForeground(new java.awt.Color(255, 255, 255));
        LblUser.setText("Email");

        LblPassword.setForeground(new java.awt.Color(255, 255, 255));
        LblPassword.setText("Password");

        createAccount.setFont(new java.awt.Font("Adwaita Sans", 1, 14)); // NOI18N
        createAccount.setText("Create Account");
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });

        LblUser1.setForeground(new java.awt.Color(255, 255, 255));
        LblUser1.setText("Name Account");

        backToLogin.setBackground(new java.awt.Color(1, 44, 98));
        backToLogin.setFont(new java.awt.Font("Adwaita Sans", 1, 14)); // NOI18N
        backToLogin.setForeground(new java.awt.Color(255, 255, 255));
        backToLogin.setText("Back to Login");
        backToLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginActionPerformed(evt);
            }
        });

        emailEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailEntryActionPerformed(evt);
            }
        });

        usernameEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usernameEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameEntryActionPerformed(evt);
            }
        });

        LblCPassword.setForeground(new java.awt.Color(255, 255, 255));
        LblCPassword.setText("Confirm your Password");

        password1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        password2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailEntry, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameEntry, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LblUser1))
                            .addComponent(LblPassword)
                            .addComponent(LblUser)
                            .addComponent(LblCPassword)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(createAccount))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(backToLogin)))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addComponent(password2)
                    .addComponent(password1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblUser1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(LblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblCPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backToLogin)
                .addGap(77, 77, 77))
        );

        jPanel3.setBackground(new java.awt.Color(1, 44, 98));

        LblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblIcon.setPreferredSize(new java.awt.Dimension(512, 512));

        LblTitle.setBackground(new java.awt.Color(0, 0, 153));
        LblTitle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LblTitle.setForeground(new java.awt.Color(255, 255, 255));
        LblTitle.setText("STAAM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(LblTitle)
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(LblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(133, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(LblTitle)
                .addGap(34, 34, 34))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(LblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginActionPerformed
        windowCreator.openWindow("Login", 400, 400, new Login());
        Window window = SwingUtilities.getWindowAncestor(this);
        window.dispose();
    }//GEN-LAST:event_backToLoginActionPerformed

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        String Username , email, Password1 , Password2 ;
        Username = usernameEntry.getText().toLowerCase();
        email = emailEntry.getText();
        Password1 = password1.getText();
        Password2 = password2.getText();
        
        if("".equals(Username) || "".equals(email) || "".equals(Password1)  || "".equals(Password2) ){
            JOptionPane.showMessageDialog(null , "You are missing some input, Very what you've written" );
        }
        else if(!Database.checkEmail(email)){
            JOptionPane.showMessageDialog(null , "The email " + email + " is not Valid");
        }
        else if(!Database.checkValidUsername(Username)){
            JOptionPane.showMessageDialog(null , "User contains invalid characters" );
        }
        else{
                String query = "SELECT * FROM Usuarios where Username = ? OR Email= ? ";
                PreparedStatement stmt;
                try{
                        Connection conn = Database.getConnection();
                        stmt = conn.prepareStatement(query);
                        stmt.setString(1, Username);
                        stmt.setString(2, email);
                        ResultSet rs = stmt.executeQuery();
                        if(rs.next()){
                             if(rs.getString("Username").toLowerCase().equals(Username)){
                                  JOptionPane.showMessageDialog(null , "The user "+Username + " already exists" );
                             }
                             else{
                                  JOptionPane.showMessageDialog(null , "The email "+email+ " has already been used" );
                             }
                        }
                        else{
                            if(Password1.equals(Password2)){
                                query = "INSERT INTO Usuarios(Username ,Email , password_hash) VALUES(?,?,?)";
                                stmt = conn.prepareStatement(query);
                                stmt.setString(1, Username);
                                stmt.setString(2, email);
                                stmt.setString(3, Database.hashPasswords(Password1));
                                stmt.executeUpdate();
                                query = "SELECT * FROM Usuarios WHERE Email = ?";
                                stmt = conn.prepareStatement(query);
                                stmt.setString(1, email);
                                rs = stmt.executeQuery();
                                rs.next();
                                GlobalUser currUser = new User(rs.getInt("ID") , rs.getString("Email") , rs.getString("Username") , rs.getDouble("Balance") , rs.getDate("FechaCreacion").toString() , rs.getString("Ubicacion") , rs.getString("Telefono") , null);
                                SessionManager.login(currUser );
                                Window window = SwingUtilities.getWindowAncestor(this);
                                window.dispose();
                                JFrame ventana = new Tienda();
                                ventana.setVisible(true);
                            }
                            else{
                                JOptionPane.showMessageDialog(null , "The passwords doesn't match" );
                            }
                        }
                }
                catch (SQLException e) {
                    e.printStackTrace();
                }
                
                
        }
    }//GEN-LAST:event_createAccountActionPerformed

    private void usernameEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameEntryActionPerformed

    private void emailEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailEntryActionPerformed

    private void password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCPassword;
    private javax.swing.JLabel LblIcon;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JLabel LblUser;
    private javax.swing.JLabel LblUser1;
    private javax.swing.JButton backToLogin;
    private javax.swing.JButton createAccount;
    private javax.swing.JTextField emailEntry;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField usernameEntry;
    // End of variables declaration//GEN-END:variables
}
